[workspace]
exclude = [".cargo", "target"]
members = ["*"]
resolver = "2"

[workspace.dependencies]
dylint_linting = { package = "scout-audit-dylint-linting", version = "3.0.1" }
if_chain = "1.0.2"
scout-audit-clippy-utils = { version = "=0.2.3" }
utils = { path = "../utils" }
